# Objective:

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [2]:
# Load Datasets 
sorteos_df = pd.read_csv('../Data/downloaded/sorteos_export.csv')
premios_df = pd.read_csv('../Data/downloaded/premios_export.csv')

In [3]:
# Join datasets by 'numero_sorteo'
data_combined_df = pd.merge(premios_df, sorteos_df, on='numero_sorteo', how='inner')

# Removing column "id"
data_combined_df.drop(columns=['id'], inplace=True)

# Save the new dataset for latter analysis in AWS QuickSight
data_combined_df.to_csv('../Data/processed/data_combined.csv', index=False)

### Data imputation

In [5]:
# replace the null values with "N/A"
"""
Vendedor, ciudad and departamento are categorical variables, 
and filling them with N/A does not affect the analysis.
"""

data_combined_df['vendedor'] = data_combined_df['vendedor'].fillna("N/A")
data_combined_df['ciudad'] = data_combined_df['ciudad'].fillna("N/A")
data_combined_df['departamento'] = data_combined_df['departamento'].fillna("N/A")

data_combined_df

,numero_sorteo,numero_premiado,letras,monto,vendedor,ciudad,departamento,tipo_sorteo,fecha_sorteo,fecha_caducidad,primer_premio,segundo_premio,tercer_premio,reintegro_primer_premio,reintegro_segundo_premio,reintegro_tercer_premio
0,390,44,P,600.0,N/A,N/A,N/A,EXTRAORDINARIO,2024-06-08,2024-12-09,16780,46129,77885,0,9,5
1,390,80,DT,600.0,N/A,N/A,N/A,EXTRAORDINARIO,2024-06-08,2024-12-09,16780,46129,77885,0,9,5
2,390,129,TT,1000.0,N/A,N/A,N/A,EXTRAORDINARIO,2024-06-08,2024-12-09,16780,46129,77885,0,9,5
3,390,180,DT,600.0,N/A,N/A,N/A,EXTRAORDINARIO,2024-06-08,2024-12-09,16780,46129,77885,0,9,5
4,390,228,P,800.0,N/A,N/A,N/A,EXTRAORDINARIO,2024-06-08,2024-12-09,16780,46129,77885,0,9,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30141,3069,79331,TT,600.0,N/A,N/A,N/A,ORDINARIO,2024-12-21,2025-06-20,29956,57331,79222,6,1,2
30142,3069,79443,P,600.0,N/A,N/A,N/A,ORDINARIO,2024-12-21,2025-06-20,29956,57331,79222,6,1,2
30143,3069,79820,P,700.0,N/A,N/A,N/A,ORDINARIO,2024-12-21,2025-06-20,29956,57331,79222,6,1,2
30144,3069,79847,P,700.0,N/A,N/A,N/A,ORDINARIO,2024-12-21,2025-06-20,29956,57331,79222,6,1,2
30145,3069,79956,TT,700.0,N/A,N/A,N/A,ORDINARIO,2024-12-21,2025-06-20,29956,57331,79222,6,1,2